### ISSUE TITLE
How to clear selection programatically?

### ISSUE THREAD

**Issue by prdebski** [alsoscotland/react-super-select#121]
How can I clear selection programatically? I need to do it by clicking a button not being part of select. Setting initialValue prop to undefined does not work.

**Comment by alsoscotland** [comment]
@prdebski 
My apologies for the delay.  Started a new job last week.
at present you cannot do this.   I will try and investigate adding the initialValue to what is inspected when props update.  I am not sure what the level of complication in doing so without looking into it

**Comment by alsoscotland** [comment]
@prdebski Finally got some time to start looking at this.  I am checking for initial value change when props update so I am not certain why this is not working yet.  Should have an answer for you fairly soon

**Comment by alsoscotland** [comment]
@prdebski I was able to get a test scenario up and for me when I set initialValue to undefined I see the control clear.  I am not able to reproduce a problem.  Can you possibly give me more info about what is going on?

**Comment by alsoscotland** [comment]
@prdebski Going to close for now as I was unable to reproduce the issue

**Comment by 6079-Smith-W** [comment]
I'm still struggling with what I think @prdebski was struggling with - I can't figure a way to programmatically clear three super-selects on my form along with all the other options (This may be because I'm doing something obviously and glaringly wrong, though). I did set 'initialValue' to a property of a react state hook object:

```
    const defaultQuery = {
        startDate: "",
        endDate: "",
           ...
        status: { key: 0, statusdisp: 'Active', statusvalue: 0 }
    };
    const [formData, setForm] = useState(defaultQuery);
    ...
    <react-super-select ...
    initialValue={formData.status}
    ...
    />
```
Changing formData with setData, like `setForm(defaultQuery)` does not reset the form as I'd expect - should it continue to reference and update the super-select when initialValue is modified? that's what seems to work with other controls (?)

Again, I may be missing something obvious - I hope I am, so it will be easy for you to give me a solution

**Comment by alsoscotland** [comment]
@6079-Smith-W 
Thanks for reaching out.  I have not had bandwidth to work on this component for several years now.  It was last compatible with React@15.x.x which was before hooks.  I am not sure how it would interact in current react with hooks

**Comment by 6079-Smith-W** [comment]
> It was last compatible with [React@15.x.x](mailto:React@15.x.x) which was before hooks. I am not sure how it would interact in current react with hooks

Thanks - I think we'll just go ahead and use react-select, which was already included in my project, but my lack of experience and guidance led me to go down a path with a little less activity/community than I probably should have, to get functionailty I didn'e realize was already in react-select from another control.
