### ISSUE TITLE
Menu list is not shown in a scrollable div

### ISSUE THREAD

**Issue by xabikos** [alsoscotland/react-super-select#49]
Thank you very much for this amazing component. I really want to use it but I face a problem when trying to add the component inside a div that has overflow auto and there is not enough space for the menu to appear. In this case we need to scroll to be able to see all the options. You can see an example here 
![super select](https://cloud.githubusercontent.com/assets/487416/12476300/b13f61ce-c028-11e5-8613-f160c716c955.png)

Instead a behavior like on that follows would be better

![date](https://cloud.githubusercontent.com/assets/487416/11473104/e674d3aa-9770-11e5-8c15-d7c093cafe0a.png)

The second is react-datepicker component and they use [tether library](https://github.com/HubSpot/tether) to achieve that result

**Comment by alsoscotland** [comment]
@xabikos Thank you for the kind words about the component.
The decision to make the component an inline is an opinionated one but it was deliberate.  

I apologize that it makes it a struggle for your use case.  Unfortunately, I think the best thing I can suggest here is that you use the customClass attribute, and override the dropdown styles so that the select dropdown fits in your window when scrolled to the top.
